### ISSUE TITLE
User Tests

### ISSUE THREAD

**Issue by sivampatel** [acmutd/TrackIT#57] opened 2020-05-21 21:57 UTC
Use Jest to create testing suite for application utilizing Jest's snapshot testing functionality. 
Ex. loading up UserDashboard and expecting render to only show `<Spinner /> ` until another function is called. 

- [ ] Create at least one test case for every component
- [ ] User Dashboard tests manipulate object state to test React output
- [ ] User Dashboard tests to check functionality of "next", "previous", and "mark completed" buttons
- [ ] Tests check various buttons such as Sign Out and alerts. 
- [ ] ensure all tests are passed by the current version of the application

**Comment by harshasrikara** [comment] 2020-05-31 20:12
Duplicate of #56

**Closed by harshasrikara** 2020-05-31 20:12 UTC
Labels: test
